### ISSUE TITLE
OSError: resource not found

### ISSUE THREAD

**Issue by pafnuty** [jugyo/SublimeTextAPIHelper#1]
Thanks for the plug, but it produces just such an error in the console:

```
Traceback (most recent call last):
  File "O:\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "sublime_text_api_helper in O:\Sublime Text 3\Data\Installed Packages\Sublime Text API Helper.sublime-package", line 6, in run
  File "O:\Sublime Text 3\sublime.py", line 126, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by jugyo** [comment]
Oops, I'll take a look. Thanks.

**Comment by jugyo** [comment]
It was fixed so please reinstall. Perhaps you need to restart Sublime Text.

**Comment by pafnuty** [comment]
Thanks! Works as it should!
